["protostar.config"]
protostar_version = "0.1.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
space = [
    "./contracts/core/space.cairo",
]
random = [
    "./contracts/core/random/random.cairo",
]
random_move_ship = [
    "./contracts/ships/random_move_ship/ship.cairo",
]
static_ship = [
    "./contracts/ships/static_ship/ship.cairo",
]
basic_ship = [
    "./contracts/ships/basic_ship.cairo",
]
only_dust = [
    "./contracts/token/OnlyDust.cairo",
]
tournament = [
    "./contracts/tournament/Tournament.cairo",
]
