["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src", "src"]
target = ["./contracts"]

[profile.ci.protostar.shared_command_configs]
no_color=true

["protostar.contracts"]
battle = [
    "./contracts/core/battle/battle.cairo",
]
random = [
    "./contracts/core/random/random.cairo",
]
random_move_ship = [
    "./contracts/ships/random_move_ship/random_move_ship.cairo",
]
static_ship = [
    "./contracts/ships/static_ship/static_ship.cairo",
]
basic_ship = [
    "./contracts/ships/basic_ship/basic_ship.cairo",
]
only_dust = [
    "./contracts/tokens/only_dust/only_dust.cairo",
]
tournament = [
    "./contracts/tournament/tournament.cairo",
]
starkonquest_boarding_pass = [
    "./contracts/tokens/starkonquest_boarding_pass/starkonquest_boarding_pass.cairo",
]
account = [
    "./contracts/account/account.cairo",
]
# Cells
standard_cell = [
    "./contracts/cells/standard_cell.cairo",
]
