name: Formatting

on: push

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install cairo-lang==0.10.0
      - name: Check files formatting
        run: find contracts/ -name "*.cairo" -print0 | xargs -0 cairo-format -c
